[toolchain]

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
# cluster = "devnet"
cluster = "http://127.0.0.1:8899/"
# cluster = "mainnet"

# wallet = "./dev.json"
# wallet = "./mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/zetasbox.ts"
